apiVersion: v1
kind: Namespace
metadata:
  name: hello-static

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: hello-static
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <link rel="icon" type="image/webp" href="favicon.png"  />
      </head>
      <body>
        <h1>Hello from the Cloud</h1>
        <p>How are you doing?</p>
        <script>
          const queryDict = {};
          location.search.substr(1).split("&").forEach(function(item) {queryDict[item.split("=")[0]] = item.split("=")[1]})
          document.querySelector("h1").innerText=`Hello ${queryDict["name"]} from the Cloud`;
        </script>
      </body>
    </html>
  redirect.html: |
    <!DOCTYPE html>
    <html>
      <meta http-equiv="refresh" content="0; url=https://google.com/" />
    </html>
binaryData:
  favicon.png: |
    UklGRigGAABXRUJQVlA4TBsGAAAvH8AHAFXRzbZtsa2cc4BOyKUFUofY3R22u7u7u7u7u7u7u/syZO3Z56IGqqIEiiD0ZgjdCvAyiP4iSKlhQiLaOWXQykp3SGeUQUT8Z2SEOyb7I67TA9rAKYB6vDYq4CLyP9y9UMOX0cKqYMJT0lRFPuEugogSqESibVuGJL1wREZlpNvm2LZt2zbL9d+dfBAlSTJt9cG1n23btu334YfXtu179/R/AmQApuuE6RPWAj0VYdd8/B1vfze0tZFtZjpF7yph6UGdZIZUM+/sDq3dqYfdi1KrSXLxcLRa8fT2LN2ZvTuO9ZaHmFkK1JaWqDrNzFsGZ/5mu5yNTVYGUUHLcsgKEF6c09OVvoqOBpot0+Aiyq5OU90W+rnV2T/08PbasO8fwss2IJcnkpzqwh4vb/dQi+hn1Cb6LNx5slxYLtVEmlNooyY9E7WcA+mEM/GEM7HMw6n2mcoqEARkrWSz+YxheF2hRhl0c5t5cF7ApyQFxQPqHa8F3wga/JRU+7zKgGNV+5zuH8n3nr91riIpACAtqAo6Zhhc1aiRTWaYzs6dZIlZaQ4AqF8pWXxysIJaj8cYq/U41uiHXLojJy4BwBezCePgqo9b5fwQaVeDzOZGwSBAnVMVsy8OlQGPN+X0f0n1K0UEcCRCr7n7+2uEvdOP/47UJh7QMiXeD3wsZqgy4O3euCdtCwE/U+nM3Xm5GrtTUGvzMAFAdatFrf8iZl68K4sASKaYdXKHa4Slw9z8gq07GWgsPAD6j2XGhl4LiSoA8G+YuYtSPT7BDIduip99vZ33AeCToJvBW4e8oGAgsI4vPcu0iwDAz2xfkXwYhVc60e052V+6mCcAaKLVsn/t2jP+Luv8FQWFHE6zLej/FjXbvPE3+0DaQADko3Oy/1vjR93w5rzsr4yNE0ATrabf3UDMpWj7UmV0rN6+VI65FNH+LyowxhodIeRmqHG92D9dbV4tRVwLez30jYRNBKQZBi5Nvm6Nn3YvSb+ayCCBT2LPRRPPxdaFsoEYR0qE2OAk6WxcrSdgLERfjq6orgSpiQZrDdYkib0YDb8SXm8U4Acby9XJ+y3J0+6l6Vcb9BE07je9HvnGkwZ1BpyACAHQqbBl897JCSbf5KHxOo1GnIQwB0gbTMRNl+ee+xE/0piujd8+3r04/W4gQwS1z5SDbgfXBaFqiGMQ1gAqpkrA3SCrMuDdn3pXZZc6AY4DXI0QAUSMBNwN1K4VEN/fWK9K3m+NH3fPyf7vIehL/3uBt+gQIAkwDqBrgng98rPbTq/ci16HzgJSAL0A+qHPQ3/jUgmRejJ0Ufp9S/yUa6ZNwstvCVpi3e9al8syBKVKZftixeCXJCh0/ol/KJWUKn92e+qdtC1EUuSCcXiZq6fpfe52f71gAFVuKfg88A9M1qQAGWJncKLu8sLLYSw4v/T0T1V3lDuDk3X3p76CPRmAI+52P8vMUjpPNe91YC8BUaWU7Mh6PPEdTTuZ2LP85BQwxpiz+Ow4+sGey3Nv1qHU3Yj/28Rd9AgbpTTarr4NACjtWOKWEceyApYrsOyj8WdjkkJBwMeqFW9/VwwUpXSEmazcWSf2EkAFe9ICZrz9PwJ+qDEbu8smOUDvnG7mXO3BYqnmUfHOHMZYvctr/xU5QcFptkX1roAx9xriX3031K6LCS3neU9/L1yvf81XbM0/hrFaW4g6kQy5HdT7I/7k+dQXcSyl/kvGmMvfm+HFBR2vlm3c6RTVU/lfObijaLWynqvq1gpvYqzS47V25tqEMjBb7Z2vDuqO2Vrp5raIsVC8KyPZoJPFwi/30s1Hmelpf7WTt9rR/i9grD7gz7oVPJkpujVlVOMUpE45H1PvcxgrUnfXQuWWRXDeJXoo01mqjTAbejumVduyAqv1+Zv/iSfuye6n2Ac4frV49Tf76xhzGkcGve3+KDNS5iJgGmOt952o1j9pe1utz93wWzr7dvCMG6FrvsvqfY5jH3N45S2dY1dBRbe8okjzcjXxVNrpWUD/h/MdzR7/iGZH0P1lt3nribwcq9pWnHEdelB3lrTSP9b+q3ZzqWZzqWm13D3dnLNdMQW9KwMA
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: hello-static
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:    
      restartPolicy: Always
      containers:
      - image: nginx:stable-alpine
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-volume
        configMap:
          name: config-map

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: hello-static
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  namespace: hello-static
spec:
  ingressClassName: nginx
  rules:
  - host: "hellostatic.cluster.dphx.eu"
    http:
      paths:
        - path: /outpost.goauthentik.io
          pathType: Prefix
          backend:
            service:
              name: ak-outpost-authentik-embedded-outpost
              port:
                number: 9000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: hello-static
  annotations:
  # This should be the in-cluster DNS name for the authentik outpost service
  # as when the external URL is specified here, nginx will overwrite some crucial headers
  nginx.ingress.kubernetes.io/auth-url: |-
    http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
  # If you're using domain-level auth, use the authentication URL instead of the application URL
  nginx.ingress.kubernetes.io/auth-signin: |-
    https://hellostatic.cluster.dphx.eu/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
  nginx.ingress.kubernetes.io/auth-response-headers: |-
    Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
  nginx.ingress.kubernetes.io/auth-snippet: |
    proxy_set_header X-Forwarded-Host $http_host;


spec:
  ingressClassName: nginx
  rules:
  - host: "hellostatic.cluster.dphx.eu"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: nginx-svc
              port:
                number: 80
